services:
  - type: web
    name: bacguide-senegal
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASS
        fromSecret: DB_PASS
      - key: DB_NAME
        value: ${DB_NAME}
